version: "3"
services:
  recebimento-gtin:
    image: tomcat:8
    container_name: recebimento-gtin
    ports:
      - "9191:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: "/etc/ebean.properties"
    volumes:
      - ./build/libs/recebimento-gtin.war:/usr/local/tomcat/webapps/recebimento-gtin.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
  recebimento-gtin-rest:
    image: java:8-jre-alpine
    container_name: recebimento-gtin-rest
    ports:
      - "8989:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: "/etc/ebean.properties"
    volumes:
      - ./ebean.properties:/etc/ebean.properties
      - ./rest/build/libs/rest.jar:/rest.jar
    restart: always
    command: java -jar /rest.jar

