version: "3"
services:
  recebimento-gtin:
    image: tomcat:8
    container_name: recebimento-gtin
    ports:
      - "9191:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: "/etc/ebean.properties"
    volumes:
      - ./
      - ./recebimento-gtin.war:/usr/local/tomcat/webapps/recebimento-gtin.war
      - ./logs:/usr/local/tomcat/logs
      - ./ebean.properties:/etc/ebean.properties
    restart: always
